-- 원격 웨이팅
CREATE TABLE waiting
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id    BIGINT                   NOT NULL REFERENCES member (id), -- 신청 고객
    store_id     BIGINT                   NOT NULL REFERENCES store (id),  -- 대상 매장
    waiting_date DATE                     NOT NULL,                        -- 웨이팅 날짜 (일자별 번호 기준)
    party_count  INTEGER                  NOT NULL,                        -- 인원수
    wait_number  INTEGER                  NOT NULL,                        -- 대기번호
    status       VARCHAR(20)              NOT NULL,                        -- 상태
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,

    -- 같은 매장·같은 날 대기번호 중복 방지
    CONSTRAINT uk_waiting_store_date_number UNIQUE (store_id, waiting_date, wait_number)
);

-- 중복 신청 조회용
CREATE INDEX idx_waiting_member_store_date ON waiting (member_id, store_id, waiting_date);